### ISSUE TITLE
Modify for BOOSTXL-EDUMKII

### ISSUE THREAD

**Issue by sipsorcery** [TI-FIRST/MSP430-Gamepad#2]
How hard would it be to modify this project to work with the [BOOSTXL-EDUMKII](http://www.ti.com/tool/boostxl-edumkii)?

**Comment by willtoth** [comment]
It wouldn't be too difficult, in fact some of the functions would work out of the box. Taking a quick look at it:
- Each accelerometer axis would come out as a joystick axis
- Each joystick axis would come out as a joystick axis on the pc
- Some of the buttons would come out as buttons on the pc, if you use the correct configuration
- Modification would be required for the temp/light sensors, UART, LCD, RGB LEDs, buzzer, servo, and any of the interrupt pins that need to be inputs

Before trying this you would probably want to make sure that none of the existing configurations could damage something on the BOOSTXL-EDUMKII board. 

This could certainly be done. I would start by removing and reconfiguring the pins that need to work for a different function, then combine other example code into the project.
